project:
  type: website
  output-dir: docs

website:
  title: "Clinical Microbiology Research Group"
  navbar:
    logo: media/lab-logo.png
    logo-alt: "Lab Logo"
    title: false  # Set to true to show both logo and text
    left:
      - href: index.qmd
        text: Home
      - href: amr.qmd
        text: Bacteriology & AMR
      - href: Emerging.qmd
        text: Emerging Microbes
      - href: viro.qmd
        text: Virology & Pathobiology
      - href: fungal.qmd
        text: Fungal Infection
      - href: mycobacteria.qmd
        text: Mycobacteria
      - href: about.qmd
        text: About
format:
  html:
    theme: 
      light: cosmo
      dark: superhero
    css: styles.css
